# Generated by Django 5.2 on 2026-05-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmbeddingConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_name', models.CharField(default='documents', help_text='exemple: documents_chunk1000_bge-m3', max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('embedding_model', models.CharField(default='BAAI/bge-m3', help_text="relancer l'embedding si modificaiton", max_length=100)),
                ('chunk_size', models.IntegerField(default=1000, help_text="taille maxi des cunks (en caractères), relancer l'embedding si modificaiton")),
                ('chunk_overlap', models.IntegerField(default=200, help_text="max chunk overlap (en caractères), relancer l'embedding si modificaiton")),
                ('chunk_number', models.IntegerField(default=32, help_text='nombre maxi de chunks par batch, à réduire si cpu-only')),
            ],
            options={
                'verbose_name': 'RAG Configuration',
            },
        ),
    ]
