# Generated by Django 5.2 on 2026-05-21 10:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_name', models.CharField(default='documents', help_text='exemple: documents_chunk1000_bge-m3', max_length=100)),
                ('collection_id', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('embedding_model', models.CharField(default='BAAI/bge-m3', help_text="relancer l'embedding si modificaiton", max_length=100)),
                ('chunk_size', models.IntegerField(default=1000, help_text="taille maxi des cunks (en caractères), relancer l'embedding si modificaiton")),
                ('chunk_overlap', models.IntegerField(default=200, help_text="max chunk overlap (en caractères), relancer l'embedding si modificaiton")),
                ('chunk_number', models.IntegerField(default=32, help_text='nombre maxi de chunks par batch, à réduire si cpu-only')),
            ],
            options={
                'verbose_name': 'Collection',
            },
        ),
        migrations.AlterModelOptions(
            name='embeddingconfig',
            options={'verbose_name': 'Embedding Configuration'},
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('type_source', models.CharField(choices=[('TX', 'Fichier .txt'), ('PD', 'Fichier .pdf'), ('MD', 'Fichier .md'), ('PTX', 'Chemin vers fivhier .txt'), ('PPD', 'Chemin vers fivhier .pdf'), ('PMD', 'Chemin vers fivhier .md'), ('LYT', 'Lien Video Youtube')], max_length=20)),
                ('source_text', models.TextField(blank=True)),
                ('source_file', models.FileField(blank=True, upload_to='ingest/file/')),
                ('nb_chunks', models.IntegerField(blank=True)),
                ('nb_words', models.IntegerField(blank=True)),
                ('nb_chars', models.IntegerField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='ingest.collection')),
            ],
        ),
    ]
