# Generated by Django 5.2 on 2026-05-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0002_collection_alter_embeddingconfig_options_document'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmbeddingConfig',
        ),
        migrations.RemoveField(
            model_name='document',
            name='source_text',
        ),
        migrations.AddField(
            model_name='document',
            name='source',
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
