# Generated by Django 5.2 on 2026-05-21 17:39

import django.db.models.deletion
import ingest.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0003_delete_embeddingconfig_remove_document_source_text_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRef',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titre', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('type_source', models.CharField(choices=[('TXF', 'Fichier .txt'), ('PDF', 'Fichier .pdf'), ('MDF', 'Fichier .md'), ('TXP', 'Chemin vers fivhier .txt'), ('PDP', 'Chemin vers fivhier .pdf'), ('MDP', 'Chemin vers fivhier .md'), ('YTU', 'URL Video Youtube')], max_length=20)),
                ('source_uri', models.CharField(blank=True, max_length=1000, validators=[ingest.models.valider_uri])),
                ('source_file', models.FileField(blank=True, upload_to='ingest/file/')),
                ('nb_chunks', models.IntegerField(blank=True)),
                ('nb_words', models.IntegerField(blank=True)),
                ('nb_chars', models.IntegerField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='ingest.collection')),
            ],
        ),
        migrations.DeleteModel(
            name='Document',
        ),
    ]
