# Generated by Django 5.2 on 2026-05-21 17:55

import ingest.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0004_documentref_delete_document'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentref',
            name='nb_chars',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentref',
            name='nb_chunks',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentref',
            name='nb_words',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentref',
            name='source_file',
            field=models.FileField(blank=True, null=True, upload_to='ingest/file/'),
        ),
        migrations.AlterField(
            model_name='documentref',
            name='source_uri',
            field=models.CharField(blank=True, max_length=1000, null=True, validators=[ingest.models.valider_uri]),
        ),
    ]
