# Generated by Django 5.2 on 2026-05-28 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0005_alter_documentref_nb_chars_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentref',
            name='source_origin',
            field=models.CharField(default='default', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentref',
            name='source_type',
            field=models.CharField(choices=[('TXT', 'Fichier .txt'), ('MD', 'Fichier .md'), ('PDF', 'Fichier .pdf'), ('YT', 'Video youtube')], default='default', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documentref',
            name='timestamp',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name='documentref',
            name='video_id',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='documentref',
            name='type_source',
            field=models.CharField(choices=[('TXF', 'Fichier .txt'), ('PDF', 'Fichier .pdf'), ('MDF', 'Fichier .md'), ('TXP', 'Chemin vers fichier .txt'), ('PDP', 'Chemin vers fichier .pdf'), ('MDP', 'Chemin vers fichier .md'), ('YTU', 'URL Video Youtube'), ('OTH', 'other format')], max_length=20),
        ),
    ]
