# Generated by Django 5.2 on 2026-05-28 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0006_documentref_source_origin_documentref_source_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentref',
            name='source_uri',
        ),
        migrations.RemoveField(
            model_name='documentref',
            name='type_source',
        ),
    ]
