# Generated by Django 5.2 on 2026-06-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0007_remove_documentref_source_uri_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='metrics',
            field=models.CharField(choices=[('COSINE', 'Distance Cosinus'), ('EUCLIDEAN', 'Distance Euclidienne L2'), ('DOT_PRODUCT', 'Produit scalaire')], default='COSINE', help_text="distance entre vecteurs, relancer l'embedding si modification", max_length=20),
        ),
        migrations.AlterField(
            model_name='collection',
            name='chunk_overlap',
            field=models.IntegerField(default=200, help_text="max chunk overlap (en caractères), relancer l'embedding si modification"),
        ),
        migrations.AlterField(
            model_name='collection',
            name='chunk_size',
            field=models.IntegerField(default=1000, help_text="taille maxi des chunks (en caractères), relancer l'embedding si modification"),
        ),
        migrations.AlterField(
            model_name='collection',
            name='embedding_model',
            field=models.CharField(default='BAAI/bge-m3', help_text="relancer l'embedding si modification", max_length=100),
        ),
    ]
