# Generated by Django 5.2 on 2026-06-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0008_collection_metrics_alter_collection_chunk_overlap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentref',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
