# Generated by Django 5.2 on 2026-06-05 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0009_documentref_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaitingList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=500)),
                ('source_type', models.CharField(choices=[('TXT', 'Fichier .txt'), ('MD', 'Fichier .md'), ('PDF', 'Fichier .pdf'), ('YT', 'Video youtube'), ('OTH', 'Other')], default='OTH', max_length=20)),
                ('source_origin', models.CharField(blank=True, max_length=1000, null=True)),
                ('video_id', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(choices=[('NEW', 'Nouveau document'), ('REG', 'Document ingéré'), ('ERR', 'Introuvable')], default='NEW', max_length=3)),
                ('date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='documentref',
            name='source_type',
            field=models.CharField(choices=[('TXT', 'Fichier .txt'), ('MD', 'Fichier .md'), ('PDF', 'Fichier .pdf'), ('YT', 'Video youtube'), ('OTH', 'Other')], max_length=20),
        ),
    ]
