# Generated by Django 5.2 on 2026-06-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0010_waitinglist_alter_documentref_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentref',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentref',
            name='status',
            field=models.CharField(choices=[('NEW', 'Nouveau document'), ('REG', 'Document ingéré'), ('ERR', 'Introuvable'), ('WIP', "En cours d'ingestion")], default='NEW', max_length=3),
        ),
    ]
