# Generated by Django 5.2 on 2026-06-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RetrivConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('k', models.IntegerField(default=4, help_text='nombre de chunks retournés')),
                ('search_type', models.CharField(choices=[('similartity', 'retourne les k chunks les plus proches'), ('similarity_score_threshold', 'retourne les k chunks les plus proches filtrés par score minimum'), ('mmr', 'maximum marginal relevance')], max_length=50)),
                ('score_threshold', models.FloatField(default=0.7, help_text='score_minimum pour sélectionner un chunk')),
                ('fetch_k', models.IntegerField(default=20, help_text='chunks candidats analysés avant sélection')),
                ('lambda_mult', models.FloatField(default=0.5, help_text='0=max diversité, 1=max similarité')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
