# Generated by Django 5.2 on 2026-06-04 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('retrieval', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retrivconfig',
            name='fetch_k',
            field=models.IntegerField(default=20, help_text='avec mmr | chunks candidats analysés avant sélection'),
        ),
        migrations.AlterField(
            model_name='retrivconfig',
            name='lambda_mult',
            field=models.FloatField(default=0.5, help_text='avec mmr | 0=max diversité, 1=max similarité'),
        ),
        migrations.AlterField(
            model_name='retrivconfig',
            name='score_threshold',
            field=models.FloatField(default=0.4, help_text='avec similarity_score_threshold | score_minimum pour sélectionner un chunk'),
        ),
        migrations.AlterField(
            model_name='retrivconfig',
            name='search_type',
            field=models.CharField(choices=[('similarity', 'similarity: retourne les k chunks les plus proches'), ('similarity_score_threshold', 'similarity_score_threshold: retourne les k chunks les plus proches filtrés par score minimum'), ('mmr', 'mmr: maximum marginal relevance')], default='similarity', max_length=50),
        ),
    ]
