name: chatrag

services:
  web:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    environment:
      DJANGO_SETTINGS_MODULE: src.settings
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "8005:8000"

  db:
    image: postgres:16
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  ragdb:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_DB: ${RAGDB_NAME}
      POSTGRES_USER: ${RAGDB_USER}
      POSTGRES_PASSWORD: ${RAGDB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pgvector_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${RAGDB_USER} -d ${RAGDB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  embeddings:
    image: ghcr.io/huggingface/text-embeddings-inference:cpu-latest
    ports:
      - "8080:80"
    command: --model-id BAAI/bge-m3
    volumes:
      - hf_models:/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:80/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 20
      start_period: 120s  

  redis:
    image: redis:7-alpine    
    ports:
      - "6379:6379"        
    volumes:
      - redis_data:/data    
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]   
      interval: 10s
      timeout: 5s
      retries: 5


  celery_worker:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    command: celery -A src worker --loglevel=info --concurrency=2
    environment:
      DJANGO_SETTINGS_MODULE: src.settings
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    volumes:
      - ./media:/app/media   # accès aux fichiers uploadés

volumes:
  postgres_data:
  pgvector_data:
  hf_models:
  redis_data:
