# Generated by Django 5.2 on 2026-06-12 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemPrompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.CharField(default="Tu es un assistant expert. Réponds à la question en te basant uniquement sur le contexte fourni. Si la réponse ne s'y trouve pas, dis-le clairement.Réponds en français.", max_length=2000)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
