# Generated by Django 5.2 on 2026-06-12 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_conversation_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemprompt',
            name='prompt',
            field=models.TextField(default="Tu es un assistant expert. Réponds à la question en te basant uniquement sur le contexte fourni. Si la réponse ne s'y trouve pas, dis-le clairement.Réponds en français."),
        ),
    ]
