# Generated by Django 5.2 on 2026-06-10 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Styles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Style par défaut', max_length=50)),
                ('color_bg', models.CharField(default='#FFFFFF', help_text='couleur de fond', max_length=7)),
                ('color_header', models.CharField(default='#222999', help_text='couleur du bandeau en-tête', max_length=7)),
                ('lightcolor_text', models.CharField(default='#FFFFFF', help_text='couleur de police / fond clair', max_length=7)),
                ('darkcolor_text', models.CharField(default='#000000', help_text='couleur de police / fond foncé', max_length=7)),
                ('color_btn', models.CharField(default='#222999', help_text='couleur des boutons', max_length=7)),
                ('hovercolor_btn', models.CharField(default='#3F49D6', help_text='couleur des boutons en hover', max_length=7)),
                ('focuscolor_line', models.CharField(default='#FEF08A', help_text='surlignage de texte', max_length=7)),
                ('hovercolor_line', models.CharField(default='#FACC15', help_text='surlignage en hover', max_length=7)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
