# Generated by Django 5.2 on 2026-06-11 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_styles'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Styles',
            new_name='Style',
        ),
    ]
